language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.6.1 WP_MULTISITE=0

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 7.0
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1 PHPCS=1 CHECKJS=1 COVERAGE=1
    - php: 5.2
      env: WP_VERSION=4.5 WP_MULTISITE=1 PHPLINT=1
    - php: 7.0
      env: WP_VERSION=4.5
    - php: 7.0
      env: WP_VERSION=4.4
    - php: 7.0
      env: WP_VERSION=4.3
    - php: 5.6
      env: WP_VERSION=4.2
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.5
      env: WP_VERSION=4.5
    - php: 5.4
      env: WP_VERSION=4.5
    - php: 5.3
      env: WP_VERSION=4.5
    - php: hhvm
      env: WP_VERSION=4.5

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit


after_success:
  - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: 846050e5b28d9e84a08b025ba7129b03f94f22063a4e9a56f5aad4a53a8e56e6

notifications:
  slack: imforza:b42wXlDhskIbr60uyPENaX4o
